import Navbar from '../components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '../components/Footer'
import '../styles/App.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Joke Simulator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        
      </body>
    </html>
  )
}
